[tool.poetry]
name = "halfapi"
version = "0.0.0"
description = ""
authors = ["Joël Maizi <joel.maizi@lirmm.fr", "Maxime Alves <maxime.alves@lirmm.fr>"]

[tool.poetry.dependencies]
click = "^7.0.0"
half-orm = { git = "git@gite.lirmm.fr:/malves/halfORM.git" }
PyJWT = "^1.7.0"
python = "^3.7.0"
starlette = "^0.13.0"
uvicorn = "^0.11.0"

[tool.poetry.dev-dependencies]
pytest = "^3.4.0"
requests = "^2.0.0"

[tool.poetry.scripts]
halfapi = 'halfpi.cli:cli'
