#-*- coding: utf-8 -*-
# pylint: disable=wrong-import-order

"""The module apidb.api.view.acl povides the Acl class.

WARNING!

This file is part of the apidb package. It has been generated by the
command halfORM. To keep it in sync with your database structure, just rerun
halfORM.

More information on the half_orm library on https://github.com/collorg/halfORM.


DO NOT REMOVE OR MODIFY THE LINES BEGINING WITH:
#>>> PLACE YOUR CODE BELOW...
#<<< PLACE YOUR CODE ABOVE...

MAKE SURE YOU PLACE YOUR CODE BETWEEN THESE LINES OR AT THE END OF THE FILE.
halfORM ONLY PRESERVES THE CODE BETWEEN THESE MARKS WHEN IT IS RUN.
"""

from ...db_connector import base_relation_class

#>>> PLACE YOUR CODE BELLOW THIS LINE. DO NOT REMOVE THIS LINE!

#<<< PLACE YOUR CODE ABOVE THIS LINE. DO NOT REMOVE THIS LINE!

__RCLS = base_relation_class('api.view.acl')

class Acl( __RCLS):
    """
    __RCLS: <class 'half_orm.relation.View_ApiApiviewAcl'>
    This class allows you to manipulate the data in the PG relation:
    VIEW: "api"."api.view"."acl"
    FIELDS:
    - name:              (text)
    - http_verb:         (verb)
    - path:              (text)
    - version:           (text)
    - domain:            (text)
    - function:          (text)
    - acl_function_name: (text)
    - abs_path:          (text)
    """
    def __init__(self, **kwargs):
        super(Acl, self).__init__(**kwargs)

        #>>> PLACE YOUR CODE BELLOW THIS LINE. DO NOT REMOVE THIS LINE!
